repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/rcmdnk/pyproject-pre-commit
  rev: v0.6.1
  hooks:
    - id: ruff-lint-diff
    - id: ruff-lint
    - id: ruff-format-diff
    - id: ruff-format
    - id: ty
    - id: mdformat-check
    - id: mdformat
    - id: validate-pyproject
