[project]
name = "team27app"
version = "0.1.0"
description = "Team 27 App in Streamlit"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "authlib>=1.6.7",
    "pymongo>=4.16.0",
    "streamlit>=1.54.0",
]
